"""initial schema

Revision ID: 0e13a99299dc
Revises: 
Create Date: 2026-08-10 14:48:52.544367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0e13a99299dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('voice', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_content_hash'), 'audio_assets', ['content_hash'], unique=True)
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('patterns',
    sa.Column('expression', sa.String(length=255), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_expression'), 'patterns', ['expression'], unique=True)
    op.create_table('texts',
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_usage',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.Enum('REFERENCE_GENERATION', 'EVALUATION', 'REEVALUATION', 'CHAT', 'GRAMMAR_EXPLANATION', 'STT', 'TTS', name='ai_operation'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_imported_by'), 'import_batches', ['imported_by'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('tests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_user_id'), 'tests', ['user_id'], unique=False)
    op.create_table('text_conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'text_id', name='uq_text_conversations_user_text')
    )
    op.create_index(op.f('ix_text_conversations_text_id'), 'text_conversations', ['text_id'], unique=False)
    op.create_index(op.f('ix_text_conversations_user_id'), 'text_conversations', ['user_id'], unique=False)
    op.create_table('text_versions',
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('french_text', sa.Text(), nullable=False),
    sa.Column('exercise_type', sa.Enum('TRANSLATION', 'SITUATIONAL', name='exercise_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('B1', 'B2', 'C1', name='difficulty'), nullable=False),
    sa.Column('contexts', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('grammar_concepts', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_versions_text_id'), 'text_versions', ['text_id'], unique=False)
    op.create_table('user_learning_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_sequence', sa.Integer(), nullable=False),
    sa.Column('current_text_id', sa.UUID(), nullable=True),
    sa.Column('current_draft', sa.Text(), nullable=True),
    sa.Column('current_hint_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_text_id'], ['texts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_text_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UNSEEN', 'ACTIVE', 'WAITING_FOR_TEST_ASSIGNMENT', 'TEST_ASSIGNED', 'MASTERED', 'MANUALLY_ACQUIRED', 'DISABLED', name='text_progress_status'), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('required_score', sa.Integer(), nullable=False),
    sa.Column('required_natural_equivalents', sa.Integer(), nullable=False),
    sa.Column('times_presented', sa.Integer(), nullable=False),
    sa.Column('natural_count', sa.Integer(), nullable=False),
    sa.Column('unnatural_count', sa.Integer(), nullable=False),
    sa.Column('writing_issue_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('hint_count', sa.Integer(), nullable=False),
    sa.Column('manually_acquired', sa.Boolean(), nullable=False),
    sa.Column('perfect_learning_record', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at_exercise', sa.Integer(), nullable=True),
    sa.Column('rotation_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'text_id')
    )
    op.create_table('attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_version_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('LEARNING', 'TEST', 'RETAKE', name='attempt_mode'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('input_method', sa.Enum('KEYBOARD', 'VOICE', name='input_method'), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('max_hint_level', sa.Integer(), nullable=False),
    sa.Column('active_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['text_version_id'], ['text_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_submission_id'), 'attempts', ['submission_id'], unique=True)
    op.create_index(op.f('ix_attempts_text_version_id'), 'attempts', ['text_version_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['text_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('linguistic_references',
    sa.Column('text_version_id', sa.UUID(), nullable=False),
    sa.Column('preferred_translation', sa.Text(), nullable=False),
    sa.Column('alternatives', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('hints', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('grammar_explanation', sa.Text(), nullable=True),
    sa.Column('patterns', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['text_version_id'], ['text_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linguistic_references_text_version_id'), 'linguistic_references', ['text_version_id'], unique=True)
    op.create_table('pattern_text_versions',
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('text_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_version_id'], ['text_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pattern_id', 'text_version_id')
    )
    op.create_table('test_attempts',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='test_attempt_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_position', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_attempts_test_id'), 'test_attempts', ['test_id'], unique=False)
    op.create_table('test_texts',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'text_id'),
    sa.UniqueConstraint('user_id', 'text_id', name='uq_test_texts_user_text')
    )
    op.create_index(op.f('ix_test_texts_user_id'), 'test_texts', ['user_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_number', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('CORRECT_NATURAL', 'CORRECT_UNNATURAL', 'CORRECT_WITH_WRITING_ISSUES', 'INCORRECT', name='verdict'), nullable=False),
    sa.Column('meaning_preserved', sa.Boolean(), nullable=False),
    sa.Column('grammar_correct', sa.Boolean(), nullable=False),
    sa.Column('natural_american_english', sa.Boolean(), nullable=False),
    sa.Column('writing_issues', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('corrected_answer', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('error_categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_attempt_id'), 'evaluations', ['attempt_id'], unique=False)
    op.create_foreign_key(
        'fk_texts_current_version_id', 'texts', 'text_versions', ['current_version_id'], ['id']
    )
    op.create_foreign_key(
        'fk_attempts_active_evaluation_id', 'attempts', 'evaluations', ['active_evaluation_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attempts_active_evaluation_id', 'attempts', type_='foreignkey')
    op.drop_constraint('fk_texts_current_version_id', 'texts', type_='foreignkey')
    op.drop_index(op.f('ix_evaluations_attempt_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_test_texts_user_id'), table_name='test_texts')
    op.drop_table('test_texts')
    op.drop_index(op.f('ix_test_attempts_test_id'), table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_table('pattern_text_versions')
    op.drop_index(op.f('ix_linguistic_references_text_version_id'), table_name='linguistic_references')
    op.drop_table('linguistic_references')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_text_version_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_submission_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('user_text_progress')
    op.drop_table('user_learning_state')
    op.drop_index(op.f('ix_text_versions_text_id'), table_name='text_versions')
    op.drop_table('text_versions')
    op.drop_index(op.f('ix_text_conversations_user_id'), table_name='text_conversations')
    op.drop_index(op.f('ix_text_conversations_text_id'), table_name='text_conversations')
    op.drop_table('text_conversations')
    op.drop_index(op.f('ix_tests_user_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_import_batches_imported_by'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('texts')
    op.drop_index(op.f('ix_patterns_expression'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_audio_assets_content_hash'), table_name='audio_assets')
    op.drop_table('audio_assets')
    # ### end Alembic commands ###
