"""add is_active to users

Revision ID: 25537a013198
Revises: 0e13a99299dc
Create Date: 2026-08-11 09:50:29.049846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25537a013198'
down_revision: Union[str, None] = '0e13a99299dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
