"""scope attempt submission_id uniqueness to per-user

Revision ID: 4a1b09e6902a
Revises: 25537a013198
Create Date: 2026-08-11 09:56:04.753810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a1b09e6902a'
down_revision: Union[str, None] = '25537a013198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attempts_submission_id', table_name='attempts')
    op.create_index(op.f('ix_attempts_submission_id'), 'attempts', ['submission_id'], unique=False)
    op.create_unique_constraint('uq_attempts_user_submission', 'attempts', ['user_id', 'submission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attempts_user_submission', 'attempts', type_='unique')
    op.drop_index(op.f('ix_attempts_submission_id'), table_name='attempts')
    op.create_index('ix_attempts_submission_id', 'attempts', ['submission_id'], unique=True)
    # ### end Alembic commands ###
