"""add current_level to user_learning_state

Revision ID: 5dd23f7b8af1
Revises: 11659f8715cf
Create Date: 2026-08-11 22:51:31.352526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5dd23f7b8af1'
down_revision: Union[str, None] = '11659f8715cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_learning_state', sa.Column('current_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='difficulty'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_learning_state', 'current_level')
    # ### end Alembic commands ###
