"""add dictation tables

Revision ID: 90ac944666f1
Revises: bd9e1e60535c
Create Date: 2026-08-15 11:18:40.410630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '90ac944666f1'
down_revision: Union[str, None] = 'bd9e1e60535c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictation_attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('verdict', postgresql.ENUM('CORRECT_NATURAL', 'CORRECT_UNNATURAL', 'CORRECT_WITH_WRITING_ISSUES', 'INCORRECT', name='verdict', create_type=False), nullable=False),
    sa.Column('corrected_answer', sa.Text(), nullable=True),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'submission_id', name='uq_dictation_attempts_user_submission')
    )
    op.create_index(op.f('ix_dictation_attempts_submission_id'), 'dictation_attempts', ['submission_id'], unique=False)
    op.create_index(op.f('ix_dictation_attempts_text_id'), 'dictation_attempts', ['text_id'], unique=False)
    op.create_index(op.f('ix_dictation_attempts_user_id'), 'dictation_attempts', ['user_id'], unique=False)
    op.create_table('user_dictation_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('times_presented', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('writing_issue_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('next_review_at_exercise', sa.Integer(), nullable=True),
    sa.Column('rotation_position', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'text_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dictation_progress')
    op.drop_index(op.f('ix_dictation_attempts_user_id'), table_name='dictation_attempts')
    op.drop_index(op.f('ix_dictation_attempts_text_id'), table_name='dictation_attempts')
    op.drop_index(op.f('ix_dictation_attempts_submission_id'), table_name='dictation_attempts')
    op.drop_table('dictation_attempts')
    # ### end Alembic commands ###
