"""add correct_with_usage_note verdict and evaluation columns

Revision ID: c4a4c8672d7b
Revises: 90ac944666f1
Create Date: 2026-08-16 21:45:32.109285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4a4c8672d7b'
down_revision: Union[str, None] = '90ac944666f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE verdict ADD VALUE IF NOT EXISTS 'CORRECT_WITH_USAGE_NOTE' AFTER 'CORRECT_NATURAL'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('problematic_segment', sa.Text(), nullable=True))
    op.add_column('evaluations', sa.Column('usage_note_alternative', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'usage_note_alternative')
    op.drop_column('evaluations', 'problematic_segment')
    # ### end Alembic commands ###
    # Postgres has no DROP VALUE for enum types; removing
    # CORRECT_WITH_USAGE_NOTE would require rebuilding the type and is not
    # supported by this migration.
    raise NotImplementedError("Cannot downgrade: Postgres cannot drop enum values")
