"""add last_review_at_exercise to user_learning_state

Revision ID: ca7622b7d34f
Revises: 5dd23f7b8af1
Create Date: 2026-08-12 23:47:01.841634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca7622b7d34f'
down_revision: Union[str, None] = '5dd23f7b8af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_learning_state', sa.Column('last_review_at_exercise', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_learning_state', 'last_review_at_exercise')
    # ### end Alembic commands ###
