"""add target_level current_level_share and benched status

Revision ID: fb168f926ad7
Revises: c4a4c8672d7b
Create Date: 2026-08-18 13:42:08.429856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb168f926ad7'
down_revision: Union[str, None] = 'c4a4c8672d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE text_progress_status ADD VALUE IF NOT EXISTS 'BENCHED'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_learning_state',
        sa.Column('target_level', sa.Enum(name='difficulty', create_type=False), nullable=True),
    )
    op.add_column(
        'user_learning_state',
        sa.Column('current_level_share', sa.Float(), nullable=False, server_default='0.25'),
    )
    # ### end Alembic commands ###

    # Backfill existing users so the new 2-tier system behaves like the old
    # 3-tier one (current level + one up) until they explicitly change it.
    op.execute(
        """
        UPDATE user_learning_state
        SET target_level = (CASE current_level::text
            WHEN 'A1' THEN 'A2' WHEN 'A2' THEN 'B1' WHEN 'B1' THEN 'B2'
            WHEN 'B2' THEN 'C1' WHEN 'C1' THEN 'C2' WHEN 'C2' THEN 'C2'
            ELSE NULL END)::difficulty
        WHERE current_level IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_learning_state', 'current_level_share')
    op.drop_column('user_learning_state', 'target_level')
    # ### end Alembic commands ###
    raise NotImplementedError("Cannot downgrade: Postgres cannot drop enum values")
