import enum


class TextProgressStatus(str, enum.Enum):
    UNSEEN = "UNSEEN"
    ACTIVE = "ACTIVE"
    WAITING_FOR_TEST_ASSIGNMENT = "WAITING_FOR_TEST_ASSIGNMENT"
    TEST_ASSIGNED = "TEST_ASSIGNED"
    MASTERED = "MASTERED"
    MANUALLY_ACQUIRED = "MANUALLY_ACQUIRED"
    DISABLED = "DISABLED"
